version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins_docker
    build:
      context: jenkins_docker
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
      
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
      - ./scripts/backup-s3.sh:/scripts/backup-s3.sh
    networks: 
      - net

  db_host: # it's called DNS or IP
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=123456" 
    volumes:
      - ./db_data:/var/lib/mysql
    networks: 
      - net 
  # git:
  #   container_name: gitlab-server
  #   hostname: gitlab.nnieto.com
  #   image: gitlab/gitlab-ce
  #   volumes:
  #     - "/srv/gitlab/config:/etc/gitlab"
  #     - "/srv/gitlab/logs:/var/log/gitlab"
  #     - "/srv/gitlab/data:/var/opt/gitlab"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - net

networks:
  net: